"""empty message

Revision ID: be02f1aea370
Revises: 3ceaa252bc27
Create Date: 2016-06-24 13:58:43.275509

"""

# revision identifiers, used by Alembic.
revision = 'be02f1aea370'
down_revision = '3ceaa252bc27'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Triples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subj', sa.String(), nullable=True),
    sa.Column('pred', sa.String(), nullable=True),
    sa.Column('obj', sa.String(), nullable=True),
    sa.Column('notes', postgresql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('results')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='results_pkey')
    )
    op.drop_table('Triples')
    ### end Alembic commands ###
